version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # Mude para uma senha mais forte em produção!
      MYSQL_DATABASE: investimentos_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend # Onde está o Dockerfile do seu backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root_password_segura@db:3306/investimentos_db
    depends_on:
      - db
    volumes:
      - ./backend:/app # Mapeia sua pasta de código para dentro do contêiner para hot-reloading em desenvolvimento

volumes:
  db_data: